In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.decomposition import PCA

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [6]:
df_train.sample(5)

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
11976,11977,2550,306,25,90,32,1034,142,215,210,...,0,1,0,0,0,0,0,0,0,6
10215,10216,3391,58,16,819,181,765,230,206,104,...,0,0,0,0,0,0,1,0,0,7
7159,7160,2568,222,18,30,-4,1318,195,254,191,...,0,0,0,0,0,0,0,0,0,3
109,110,2567,333,1,0,0,1266,216,237,158,...,0,0,0,0,0,0,0,0,0,2
3428,3429,2278,115,43,255,167,900,249,159,0,...,0,0,0,0,0,0,0,0,0,4